name: MacOS Maven build

on: 
  pull_request:
    paths-ignore:
      - 'tailormap-components/**'

jobs:
  build:
    name: MacOS Java ${{ matrix.java }}
    runs-on: [macos-10.15]
    strategy:
      matrix:
        java: [11]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        mvn -B test -fae
        mvn -B verify -fae -e

    - name: Cleanup snapshots
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
