name: Windows Maven build

on: [pull_request,push]
  paths-ignore:
    - 'tailormap-components/**'

jobs:
  build:
    name: Windows Java ${{ matrix.java }}
    runs-on: [windows-latest]
    strategy:
      matrix:
        java: [11]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: |
        mvn -B test -fae
        mvn -B verify -fae -e
